data_app/urls.py
from django.urls import path
from . import views

app_name = 'data_app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:id>/posted/', views.posted, name='posted')
]

data_visualizer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('data_app/', include('data_app.urls'))
]

data_app/models.py
import datetime

from django.db import models


# Create your models here.
from django.utils import timezone


class Item(models.Model):
    title = models.CharField(max_length=50)
    text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(default=timezone.now())
    is_valid = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def has_one_word_title(self):
        return self.title.split(' ').__len__() == 1

    def is_published_recently(self):
        return self.pub_date >= timezone.now()-datetime.timedelta(days=1)

data_app/views.py
# Create your views here.
import json

from django.http import JsonResponse, HttpResponse
from django.views import generic

from .models import Item


class IndexView(generic.ListView):
    """ E' possibile in alternativa a definire questi attributi fare override dei
     metodi corrispondenti
     es: queryset corrisponde al metodo get_queryset() """
    model = Item
    template_name = 'index.html'
    context_object_name = 'all_objects_list'
    queryset = Item.objects.filter(is_valid=True)


# Risponde alla chiamata post axios facendo una query sul DB e
# inviando la risposta al client in formato JSON
def posted(request, id):
    # data = request.body.decode()
    # data2 = [block for block in data.split('{')]
    obj = Item.objects.get(pk=id)
    #response = {
    #    'title': obj.title,
    #    'text': obj.text
    #}
    # id = data['id']
    return HttpResponse(obj.title, content_type='text/plain')

templates/index.html
{% extends 'masterpage.html' %}
{% block content %}
<div id="app" class="card text-center">
    <div class="card-header title-bar"><b>[[ title ]]</b></div>
    <div class="card-body">
        <div v-bind="all_objects_list">
            {% if all_objects_list %}
            <ol>
                {% for obj in all_objects_list %}
                <li>
                    {{ obj.title }} {{ obj.text }} {{ obj.pub_date }} {{ obj.is_valid }}
                </li>
                {% endfor %}
            </ol>
            {% endif %}
        </div>
        <form @submit="formSubmit" method="post">
            <label>
                <input type="number" name="input" v-model="identifier" class="text-center">
            </label>
            <div>[[ identifier ]]</div>
            <button class="button success">Submit</button><br>
            <strong>Output:</strong>
        </form>
        <pre v-html="output"></pre>
    </div>
</div>
<script>
    axios.defaults.xsrfCookieName = 'csrftoken';
    axios.defaults.xsrfHeaderName = 'X-CSRFToken';
    var app = new Vue({
        delimiters: ['[[', ']]'],
        el: '#app',
        data: {
            title: 'Data retrieved from DB will be available once you\'ve clicked the button below',
            identifier: 0,
            output: ''
        },
        methods: {
            formSubmit(e) {
                e.preventDefault();
                let currentObj = this;
                let url = "{% url 'data_app:posted' input='1' %}".replace('1', currentObj.identifier);
                axios.post(url)
                    .then( response => {
                        //currentObj.output = response.data['title']+': '+response.data['text']
                        currentObj.output = response
                        console.log(response);
                    })
                    .catch( error => {
                        //alert('Ricevuta risposta, ma con problema...');
                        currentObj.output = error.response;
                        console.log(error);
                    })
                //return false;
            }
        }
    });
</script>
{% endblock %}

templates/masterpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://unpkg.com/vue"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.1/css/foundation.min.css">
    <style>
        .center{
            display: flex;
            align-items: center;
            justify-content: center;
        }
    </style>
    <title>Home-page</title>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>